In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('/kaggle/input/iris/Iris.csv')

In [3]:
data.head
data = np.array(data)

In [4]:
data = np.delete(data,0,1)
data


array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

In [5]:
m, n = data.shape
np.random.shuffle(data) 

In [6]:
#data

In [7]:
data_dev = data[0:140].T

Y_dev = data_dev[4]
X_dev = data_dev[:4]
X_dev = X_dev


In [8]:
Y_dev

array(['Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virgi

In [9]:
Y_dev = np.unique(Y_dev, return_inverse=True)[1].tolist()
Y_dev = np.array(Y_dev)
Y_dev

array([2, 2, 1, 2, 0, 1, 0, 2, 2, 0, 1, 0, 0, 2, 2, 2, 1, 2, 2, 1, 1, 0,
       2, 2, 0, 1, 1, 1, 1, 0, 2, 1, 1, 0, 2, 0, 1, 2, 0, 2, 2, 2, 1, 0,
       2, 2, 2, 0, 1, 1, 2, 1, 1, 0, 1, 0, 1, 1, 2, 0, 2, 1, 0, 2, 2, 1,
       2, 0, 1, 0, 1, 1, 1, 2, 0, 2, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 1,
       0, 0, 1, 0, 0, 2, 2, 0, 1, 0, 0, 1, 2, 0, 2, 0, 0, 1, 1, 1, 1, 0,
       2, 2, 1, 2, 2, 2, 0, 0, 1, 1, 1, 0, 1, 1, 2, 0, 2, 0, 2, 0, 1, 0,
       1, 2, 1, 1, 2, 1, 0, 1])

In [10]:
data_train = data[140:m].T

Y_train = data_train[4]
X_train = data_train[:4]
X_train = X_train
X_train.shape

(4, 10)

In [11]:
Y_train = np.unique(Y_train, return_inverse=True)[1].tolist()
Y_train = np.array(Y_train)


In [12]:
def initial_params():
    w1 = np.random.rand(10,4)-0.5
    w2 = np.random.rand(3,10)-0.5
    b1 = np.random.rand(10,1)-0.5
    b2 = np.random.rand(3,1)-0.5
    return w1,w2,b1,b2

def relu(z):
    return np.maximum(0,z)

def softmax(z):
    return np.exp(z)/np.sum(np.exp(z))
  
def fwd_prop(w1,w2,b1,b2,x):
    z1 = w1.dot(x) + b1
    a1 = relu(z1)
    z2 = w2.dot(a1) + b2
    #print(z2.shape)
    a2 = softmax(z2)
    #print(a2.shape)
    return z1,a1,z2,a2  


def deriv_relu(z):
    return z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, 3))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def back_prop(z1, a1, z2, a2, w1, w2, x, y):
    #one_hot_y = one_hot(y)
    dz2 = a2 #- one_hot_y
    dw2 = 1/m * dz2.dot(a1.T)
    db2 = 1/m * np.sum(dz2)
    
    dz1 = w2.T.dot(dz2) * deriv_relu(z1)
    dw1 = 1/m * dz1.dot(x.T)
    db1 = 1/m * np.sum(dz1)
    
    return dw1,dw2,db1,db2

def update_params(w1,b1,w2,b2,dw1,db1,dw2,db2,alpha):
    w1 = w1 - alpha * dw1
    b1 = b1 - alpha * db1
    w2 = w2 - alpha * dw2
    b2 = b2 - alpha * db2
    return w1,w2,b1,b2

def prediction(a2):
    #print(a2)
    #print(np.argmax(a2,1))
    return np.argmax(a2,0)

def accuracy(pred,y):
    #print(pred,y)
    return np.sum(pred == y)/y.size

def best(a,b,w1,b1,w2,b2):
    if(b>a):
        wa = w1
        ba = b1
        wb = w2
        bb = b2
    return b    
    

In [13]:


def gradient_decent(x, y, epochs, alpha):
    w1, w2, b1, b2 = initial_params()
    k = 0
    for i in range(epochs):
        
       
        z1, a1, z2, a2 = fwd_prop(w1, w2, b1, b2, x)
        k = best(k,accuracy(prediction(a2),y),w1, b1, w2, b2)
        dw1, dw2, db1, db2 = back_prop(z1, a1, z2, a2, w1, w2, x, y)
        w1, w2, b1, b2 = update_params(w1,b1,w2,b2,dw1,db1,dw2,db2,alpha)
        
        
        if i % 10 == 0 :
           
            print('iteration:', i)
            print('accuracy:' ,accuracy(prediction(a2),y))
           
            
            print('best:',k)
            k = accuracy(prediction(a2),y)
       
    return w1,w2,b1,b2       
            
        

In [14]:
w1, w2, b1, b2 = gradient_decent(X_dev.astype(float), Y_dev, 700, 0.1)

iteration: 0
accuracy: 0.32857142857142857
best: 0.32857142857142857
iteration: 10
accuracy: 0.32857142857142857
best: 0.32857142857142857
iteration: 20
accuracy: 0.32857142857142857
best: 0.32857142857142857
iteration: 30
accuracy: 0.32857142857142857
best: 0.32857142857142857
iteration: 40
accuracy: 0.32857142857142857
best: 0.32857142857142857
iteration: 50
accuracy: 0.32857142857142857
best: 0.32857142857142857
iteration: 60
accuracy: 0.32857142857142857
best: 0.32857142857142857
iteration: 70
accuracy: 0.32857142857142857
best: 0.32857142857142857
iteration: 80
accuracy: 0.32857142857142857
best: 0.32857142857142857
iteration: 90
accuracy: 0.32857142857142857
best: 0.32857142857142857
iteration: 100
accuracy: 0.32857142857142857
best: 0.32857142857142857
iteration: 110
accuracy: 0.32857142857142857
best: 0.32857142857142857
iteration: 120
accuracy: 0.32857142857142857
best: 0.32857142857142857
iteration: 130
accuracy: 0.32857142857142857
best: 0.32857142857142857
iteration: 140
ac

In [15]:
def make_predictions(X, w1, b1, w2, b2):
    _, _, _, a2 = fwd_prop(w1, w2, b1, b2, X)
    predictions = prediction(a2)
    return predictions

In [16]:
make_predictions(X_train.astype(float), w1, b1, w2, b2)

array([1, 0, 0, 0, 1, 1, 1, 1, 2, 0])

In [17]:
Y_train

array([0, 1, 1, 1, 0, 0, 0, 0, 0, 1])